import type { CityAISnapshot, CityEvent, NewsCategory, SnapshotEntity } from "../model/AI";
import { defaultAIConfig } from "../model/AI";
import type { City } from "../model/City";
import { deriveDistrictGdpLeaderboard } from "../model/CityInformation";

export type { CityAISnapshot } from "../model/AI";
export interface PrepareEventsOptions { minimumImportance?: number; maximumEvents?: number }
export const DEFAULT_EVENT_IMPORTANCE_THRESHOLD = defaultAIConfig.eventImportanceThreshold;
export const DEFAULT_MAXIMUM_ISSUE_EVENTS = 8;

let fallbackSequence = 0;
function idFor(type: string, entityId: string, timestamp: number): string { return `event-${timestamp}-${type}-${entityId}-${globalThis.crypto?.randomUUID?.() ?? ++fallbackSequence}`; }
function center(points: readonly { x: number; y: number }[]): { x: number; y: number } | undefined { if (!points.length) return undefined; return points.reduce((sum, point) => ({ x: sum.x + point.x / points.length, y: sum.y + point.y / points.length }), { x: 0, y: 0 }); }

export function createCitySnapshot(city: City, capturedAt = Date.now()): CityAISnapshot {
  const districtRanks = new Map(deriveDistrictGdpLeaderboard(city).map((district) => [district.id, district.rank])); const railNodes = new Map((city.railNodes ?? []).map((node) => [node.id, node]));
  const roadNodes = new Map(city.roadNodes.map((node) => [node.id, node]));
  const roadEdges = new Map(city.roadEdges.map((edge) => [edge.id, edge]));
  const roadCenter = (segmentIds: readonly string[]) => {
    const nodeIds = new Set<string>();
    for (const id of segmentIds) { const edge = roadEdges.get(id); if (edge) { nodeIds.add(edge.startNodeId); nodeIds.add(edge.endNodeId); } }
    return center([...nodeIds].flatMap((id) => { const node = roadNodes.get(id); return node ? [node] : []; }));
  };
  return structuredClone({
    cityId: city.id, capturedAt,
    universities: city.universities.map((item) => ({ id: item.id, name: item.name, ranking: item.ranking })),
    campuses: city.zones.filter((zone) => Boolean(zone.universityId)).map((zone) => ({ id: zone.id, name: zone.name ?? "", parentId: zone.universityId, type: zone.campusRole, position: center(zone.polygon) })),
    hospitals: city.hospitals.map((item) => ({ id: item.id, name: item.name, ranking: item.ranking, specialtySignature: [...item.specialties].sort().join("\u001f") })),
    hospitalCampuses: city.zones.filter((zone) => Boolean(zone.hospitalId)).map((zone) => ({ id: zone.id, name: zone.name ?? "", parentId: zone.hospitalId, type: zone.hospitalCampusRole, position: center(zone.polygon) })),
    companies: city.companies.map((item) => ({ id: item.id, name: item.name, marketValue: item.marketValue, marketValueRank: item.marketValueRank, position: city.facilities.find((facility) => facility.companyId === item.id && facility.isCompanyHeadquarters)?.position ?? city.facilities.find((facility) => facility.companyId === item.id)?.position })),
    facilities: [...city.facilities.map((item) => ({ id: item.id, name: item.name, parentId: item.companyId ?? item.affiliatedUniversityId ?? item.universityZoneId, type: item.isCompanyHeadquarters ? "company-headquarters" : item.type, position: item.position, relatedIds: [item.companyId, item.affiliatedUniversityId, item.universityZoneId].filter((id): id is string => Boolean(id)) })), ...city.zones.filter((zone) => ["high-speed-rail-station", "train-station", "airport"].includes(zone.type)).map((zone) => ({ id: zone.id, name: zone.name ?? "", type: zone.type, position: center(zone.polygon) }))],
    districts: city.districts.map((item) => ({ id: item.id, name: item.name, gdp: item.gdp, gdpYear: item.gdpYear, districtRank: districtRanks.get(item.id), position: center(item.points) })),
    roads: city.roads.map((item) => ({ id: item.id, name: item.name, type: `${item.category}:${item.subtype}`, position: roadCenter(item.segmentIds) })),
    busLines: city.busLines.map((item) => ({ id: item.id, name: item.name, relatedIds: [...item.stopIds], position: center(city.busStops.filter((stop) => item.stopIds.includes(stop.id)).map((stop) => stop.position)) })),
    busStops: city.busStops.map((item) => ({ id: item.id, name: item.name, parentId: item.lineId, position: item.position })),
    railLines: (city.railLines ?? []).map((item) => ({ id: item.id, name: item.name, type: item.system, relatedIds: [...item.stationIds], position: center((city.railStations ?? []).filter((station) => item.stationIds.includes(station.id)).map((station) => railNodes.get(station.nodeId)).filter((node): node is NonNullable<typeof node> => Boolean(node))) })),
    railStations: (city.railStations ?? []).map((item) => ({ id: item.id, name: item.name, type: item.system, relatedIds: (city.railLines ?? []).filter((line) => line.stationIds.includes(item.id)).map((line) => line.id).sort(), position: railNodes.get(item.nodeId) })),
  });
}

function cityEvent(timestamp: number, type: string, category: NewsCategory, entity: SnapshotEntity, importance: number, payload: Record<string, unknown> = {}, relatedIds: readonly string[] = []): CityEvent { const id = idFor(type, entity.id, timestamp); return { id, timestamp, type, category, importance: Math.max(0, Math.min(100, Math.round(importance))), relatedEntityIds: [...new Set([entity.id, ...relatedIds].filter(Boolean))], payload: { entityId: entity.id, entityName: entity.name, ...payload, sourceEventIds: [id] }, location: entity.position ? { ...entity.position } : undefined }; }
function additions(current: readonly SnapshotEntity[], previous: readonly SnapshotEntity[]): SnapshotEntity[] { const ids = new Set(previous.map((item) => item.id)); return current.filter((item) => !ids.has(item.id)); }
function meaningfulValueChange(before: number | null | undefined, after: number | null | undefined): boolean { if (before === after) return false; if (before === undefined || before === null || after === undefined || after === null) return true; return before === 0 ? after !== 0 : Math.abs(after - before) / Math.abs(before) >= 0.05; }
function valueImportance(before: number | null | undefined, after: number | null | undefined, base: number): number { if (before === undefined || before === null || after === undefined || after === null || before === 0) return base + 20; return Math.min(100, base + Math.round(Math.abs(after - before) / Math.abs(before) * 100)); }
function rankingEvents(current: readonly SnapshotEntity[], previous: readonly SnapshotEntity[], field: "ranking" | "marketValueRank" | "districtRank", category: NewsCategory, timestamp: number): CityEvent[] { const old = new Map(previous.map((item) => [item.id, item])); return current.flatMap((item) => { const before = old.get(item.id)?.[field]; const after = item[field]; if (before === after) return []; const movement = typeof before === "number" && typeof after === "number" ? Math.abs(after - before) : 0; const topTen = typeof before === "number" && before <= 10 || typeof after === "number" && after <= 10; return [cityEvent(timestamp, field === "districtRank" ? "district-ranking-changed" : "ranking-changed", category, item, Math.min(100, 45 + (movement >= 2 ? 15 : 0) + Math.min(20, movement * 3) + (topTen ? 15 : 0)), { metric: field, oldValue: before ?? null, newValue: after ?? null })]; }); }
function facilityImportance(type = ""): number { const value = type.toLowerCase(); if (["coffee-shop", "cafe", "parking", "store", "bakery", "bar", "restaurant"].includes(value)) return value === "parking" ? 10 : 5; if (["laboratory", "lab", "research-center"].includes(value)) return 60; if (["college", "school"].includes(value)) return 55; if (value === "company-headquarters") return 70; if (["airport", "international-airport"].includes(value)) return 95; if (["high-speed-rail-station", "high-speed-station"].includes(value)) return 85; if (value === "train-station") return 75; if (["stadium", "government-office", "community-center", "museum", "library", "hospital", "research-institute"].includes(value)) return 35; return 20; }

function creationEvents(current: CityAISnapshot, previous: CityAISnapshot): CityEvent[] { const time = current.capturedAt; return [
  ...additions(current.universities, previous.universities).map((item) => cityEvent(time, "university-created", "university", item, 70, { entityType: "university" })),
  ...additions(current.campuses, previous.campuses).map((item) => cityEvent(time, "campus-created", "university", item, 45, { entityType: "campus" }, [item.parentId ?? ""])),
  ...additions(current.hospitals, previous.hospitals).map((item) => cityEvent(time, "hospital-created", "healthcare", item, 70, { entityType: "hospital" })),
  ...additions(current.hospitalCampuses, previous.hospitalCampuses).map((item) => cityEvent(time, "hospital-campus-created", "healthcare", item, 75, { entityType: "hospital-campus" }, [item.parentId ?? ""])),
  ...additions(current.companies, previous.companies).map((item) => cityEvent(time, "company-created", "business", item, 70, { entityType: "company" })),
  ...additions(current.facilities, previous.facilities).map((item) => cityEvent(time, "facility-created", item.type === "company" || item.type === "company-headquarters" || item.type === "research-center" ? "business" : item.parentId ? "university" : item.type?.includes("rail") || item.type?.includes("train-station") || item.type?.includes("airport") ? "transport" : "city", item, facilityImportance(item.type), { entityType: "facility", facilityType: item.type }, item.relatedIds)),
  ...additions(current.districts, previous.districts).map((item) => cityEvent(time, "district-created", "district", item, 35, { entityType: "district" })),
  ...additions(current.busLines, previous.busLines).map((item) => cityEvent(time, "bus-line-opened", "transport", item, 45, { entityType: "bus-line" }, item.relatedIds)),
  ...additions(current.railLines, previous.railLines).map((item) => cityEvent(time, "rail-line-opened", "transport", item, item.type === "metro" ? 60 : 80, { entityType: item.type === "metro" ? "metro-line" : "rail-line", transportSystem: item.type }, item.relatedIds)),
  ...additions(current.railStations, previous.railStations).map((item) => cityEvent(time, "rail-station-enabled", "transport", item, item.type === "metro" ? 55 : 85, { entityType: item.type === "metro" ? "metro-station" : "rail-station", transportSystem: item.type }, item.relatedIds)),
  ...additions(current.roads, previous.roads).filter((item) => item.type?.startsWith("highway:") || item.type?.endsWith(":highway") || item.type?.endsWith(":large")).map((item) => cityEvent(time, "road-completed", "transport", item, item.type?.includes("highway") ? 70 : 35, { entityType: "road", roadType: item.type })),
]; }

function changeEvents(current: CityAISnapshot, previous: CityAISnapshot): CityEvent[] { const time = current.capturedAt; const companies = new Map(previous.companies.map((item) => [item.id, item])); const districts = new Map(previous.districts.map((item) => [item.id, item])); const hospitals = new Map(previous.hospitals.map((item) => [item.id, item])); return [
  ...rankingEvents(current.universities, previous.universities, "ranking", "university", time), ...rankingEvents(current.hospitals, previous.hospitals, "ranking", "healthcare", time), ...rankingEvents(current.companies, previous.companies, "marketValueRank", "business", time), ...rankingEvents(current.districts, previous.districts, "districtRank", "district", time),
  ...current.companies.flatMap((item) => { const before = companies.get(item.id); return before && meaningfulValueChange(before.marketValue, item.marketValue) ? [cityEvent(time, "market-value-changed", "business", item, valueImportance(before.marketValue, item.marketValue, 45), { metric: "marketValue", oldValue: before.marketValue ?? null, newValue: item.marketValue ?? null })] : []; }),
  ...current.districts.flatMap((item) => { const before = districts.get(item.id); return before && meaningfulValueChange(before.gdp, item.gdp) ? [cityEvent(time, "gdp-changed", "district", item, valueImportance(before.gdp, item.gdp, 45), { metric: "gdp", oldValue: before.gdp ?? null, newValue: item.gdp ?? null, oldYear: before.gdpYear, year: item.gdpYear })] : []; }),
  ...current.hospitals.flatMap((item) => { const before = hospitals.get(item.id); if (!before || before.specialtySignature === item.specialtySignature) return []; const oldValues = before.specialtySignature?.split("\u001f").filter(Boolean) ?? []; const newValues = item.specialtySignature?.split("\u001f").filter(Boolean) ?? []; return [cityEvent(time, "specialties-changed", "healthcare", item, 55, { added: newValues.filter((value) => !oldValues.includes(value)), removed: oldValues.filter((value) => !newValues.includes(value)) })]; }),
]; }
function busStopEvents(current: CityAISnapshot, previous: CityAISnapshot): CityEvent[] { const lines = new Map(current.busLines.map((line) => [line.id, line])); return additions(current.busStops, previous.busStops).map((stop) => { const line = lines.get(stop.parentId ?? "") ?? { id: stop.parentId ?? stop.id, name: "未命名公交线路" }; return cityEvent(current.capturedAt, "bus-stop-created", "transport", line, 15, { entityType: "bus-line", count: 1, stopIds: [stop.id], stopNames: [stop.name] }, [stop.id]); }); }
export function diffCitySnapshots(current: CityAISnapshot, previous?: CityAISnapshot): CityEvent[] { if (!previous) return []; if (current.cityId !== previous.cityId) throw new Error("cannot compare snapshots from different cities"); return [...creationEvents(current, previous), ...changeEvents(current, previous), ...busStopEvents(current, previous)]; }
function sourceIds(event: CityEvent): string[] { return Array.isArray(event.payload.sourceEventIds) ? event.payload.sourceEventIds.filter((id): id is string => typeof id === "string") : [event.id]; }
export function mergeCityEvents(events: readonly CityEvent[]): CityEvent[] { const result = new Map<string, CityEvent>(); for (const source of events) { if (!source.id || !source.type || !Number.isFinite(source.importance) || !Array.isArray(source.relatedEntityIds)) continue; const entityId = typeof source.payload.entityId === "string" ? source.payload.entityId : source.relatedEntityIds[0] ?? "unknown"; const key = entityId; const existing = result.get(key); if (!existing) { result.set(key, structuredClone(source)); continue; } const sourceEventIds = [...new Set([...sourceIds(existing), ...sourceIds(source)])]; const count = (typeof existing.payload.count === "number" ? existing.payload.count : 1) + (typeof source.payload.count === "number" ? source.payload.count : 1); const differentTypes = existing.type !== source.type; const payload: Record<string, unknown> = { ...existing.payload, ...source.payload, count, sourceEventIds, ...(differentTypes ? { eventTypes: [...new Set([...(Array.isArray(existing.payload.eventTypes) ? existing.payload.eventTypes.map(String) : [existing.type]), source.type])], changes: [...(Array.isArray(existing.payload.changes) ? existing.payload.changes : [existing.payload]), source.payload] } : {}) }; for (const field of ["stopIds", "stopNames"] as const) payload[field] = [...new Set([...(Array.isArray(existing.payload[field]) ? existing.payload[field] : []), ...(Array.isArray(source.payload[field]) ? source.payload[field] : [])].map(String))]; const primary = source.importance > existing.importance ? source : existing; result.set(key, { ...primary, id: idFor(differentTypes ? "entity-events-merged" : existing.type, entityId, Math.max(existing.timestamp, source.timestamp)), type: differentTypes ? "entity-events-merged" : existing.type, timestamp: Math.max(existing.timestamp, source.timestamp), importance: Math.min(100, Math.max(existing.importance, source.importance) + 8), relatedEntityIds: [...new Set([...existing.relatedEntityIds, ...source.relatedEntityIds])], payload, location: primary.location ?? source.location ?? existing.location }); } return [...result.values()]; }
export function prepareTopCityEvents(events: readonly CityEvent[], options: PrepareEventsOptions = {}): CityEvent[] { const minimumImportance = options.minimumImportance ?? DEFAULT_EVENT_IMPORTANCE_THRESHOLD; const maximumEvents = options.maximumEvents ?? DEFAULT_MAXIMUM_ISSUE_EVENTS; if (!Number.isFinite(minimumImportance) || minimumImportance < 0 || minimumImportance > 100 || !Number.isInteger(maximumEvents) || maximumEvents < 1 || maximumEvents > 8) throw new Error("invalid event preparation options"); return mergeCityEvents(events).filter((event) => event.importance >= minimumImportance).sort((left, right) => right.importance - left.importance || left.timestamp - right.timestamp || left.id.localeCompare(right.id)).slice(0, maximumEvents); }
export class CityEventCollector { public snapshot(city: City, capturedAt = Date.now()): CityAISnapshot { return createCitySnapshot(city, capturedAt); } public collect(current: City | CityAISnapshot, previous?: City | CityAISnapshot): CityEvent[] { const currentSnapshot = "cityId" in current ? current : createCitySnapshot(current); const previousSnapshot = previous ? "cityId" in previous ? previous : createCitySnapshot(previous) : undefined; return diffCitySnapshots(currentSnapshot, previousSnapshot); } public prepare(events: readonly CityEvent[], options?: PrepareEventsOptions): CityEvent[] { return prepareTopCityEvents(events, options); } }
export const SnapshotDiff = Object.freeze({ compare: diffCitySnapshots });
