import { Building2, Copy, FlipHorizontal2, Maximize, Minimize, PenTool, PencilRuler, RotateCcw, RotateCw } from "lucide-react";
import { useEditorStore } from "../../app/store/editorStore";
import type { Editor } from "../../editor/Editor";
import type { TranslationKey } from "../../i18n";
import type { BuildingStyle, BuildingType } from "../../model/City";
import type { BuildingPreset } from "../../geometry/BuildingGeometry";
import { soundManager } from "../../services/SoundManager";

const presets: BuildingPreset[] = ["rectangle", "l", "u", "h", "courtyard"];
const presetKeys: Record<BuildingPreset, TranslationKey> = { rectangle: "building.preset.rectangle", l: "building.preset.l", u: "building.preset.u", h: "building.preset.h", courtyard: "building.preset.courtyard" };
const typeKeys: Record<BuildingType, TranslationKey> = { residential: "building.type.residential", commercial: "building.type.commercial", education: "building.type.education", medical: "building.type.medical", government: "building.type.government", industrial: "building.type.industrial", office: "building.type.office", public: "building.type.public", custom: "building.type.custom" };
const styleKeys: Record<BuildingStyle, TranslationKey> = { modern: "building.style.modern", chinese: "building.style.chinese", classical: "building.style.classical", industrial: "building.style.industrial", custom: "building.style.custom" };

export function BuildingToolPalette({ editor, t }: { editor: Editor; t: (key: TranslationKey) => string }) {
  const store = useEditorStore(); const selectedId = editor.selection?.kind === "building" ? editor.selection.id : undefined; const click = () => soundManager.playClick();
  return <aside className="road-palette building-palette glass-panel" aria-label={t("tools.buildings")}>
    <div className="palette-title"><Building2 size={16}/><span>{t("tools.buildings")}</span></div>
    <div className="palette-toggle building-mode-toggle"><button className={store.buildingMode === "preset" ? "is-active" : ""} type="button" onClick={() => { click(); store.setBuildingMode("preset"); }}><Building2 size={16}/><small>{t("building.place")}</small></button><button className={store.buildingMode === "free" ? "is-active" : ""} type="button" onClick={() => { click(); store.setBuildingMode("free"); }}><PenTool size={16}/><small>{t("building.free")}</small></button><button className={store.buildingMode === "edit" ? "is-active" : ""} type="button" onClick={() => { click(); store.setBuildingMode("edit"); }}><PencilRuler size={16}/><small>{t("building.edit")}</small></button></div>
    {store.buildingMode === "preset" && <><small className="zone-section-label">{t("building.preset")}</small><div className="building-preset-grid">{presets.map((preset) => <button className={store.buildingPreset === preset ? "is-active" : ""} type="button" key={preset} onClick={() => { click(); store.setBuildingPreset(preset); }}><b>{preset === "rectangle" ? "R" : preset.toUpperCase()}</b><span>{t(presetKeys[preset])}</span></button>)}</div></>}
    {store.buildingMode !== "edit" && <><label><Building2 size={15}/><select value={store.buildingType} title={t("properties.buildingType")} onChange={(event) => store.setBuildingType(event.target.value as BuildingType)}>{(Object.keys(typeKeys) as BuildingType[]).map((type) => <option key={type} value={type}>{t(typeKeys[type])}</option>)}</select></label><label><span>ST</span><input value={store.buildingSubtype} title={t("building.subtype")} placeholder={t("building.subtype")} onChange={(event) => store.setBuildingSubtype(event.target.value)}/></label><label><PencilRuler size={15}/><select value={store.buildingStyle} title={t("building.style")} onChange={(event) => store.setBuildingStyle(event.target.value as BuildingStyle)}>{(Object.keys(styleKeys) as BuildingStyle[]).map((style) => <option key={style} value={style}>{t(styleKeys[style])}</option>)}</select></label><label><span>W</span><div className="palette-width"><input type="number" min="4" max="500" step="0.5" value={store.buildingWidth} onChange={(event) => store.setBuildingWidth(Number(event.target.value))}/><span>m</span></div></label><label><span>D</span><div className="palette-width"><input type="number" min="4" max="500" step="0.5" value={store.buildingDepth} onChange={(event) => store.setBuildingDepth(Number(event.target.value))}/><span>m</span></div></label><label><span>F</span><input type="number" min="1" max="200" value={store.buildingFloors} title={t("building.floors")} onChange={(event) => store.setBuildingFloors(Number(event.target.value))}/></label><label><span>H</span><div className="palette-width"><input type="number" min="1" max="1000" step="0.5" value={store.buildingHeight} onChange={(event) => store.setBuildingHeight(Number(event.target.value))}/><span>m</span></div></label><label className="palette-check"><span><input type="checkbox" checked={store.buildingSnapToRoad} onChange={(event) => store.setBuildingSnapToRoad(event.target.checked)}/>{t("building.snapToRoad")}</span></label>{store.buildingSnapToRoad && <label><span>S</span><div className="palette-width"><input type="number" min="0" max="200" step="0.5" value={store.buildingSetback} onChange={(event) => store.setBuildingSetback(Number(event.target.value))}/><span>m</span></div></label>}</>}
    {store.buildingMode === "edit" && <><label className="palette-check"><span><input type="checkbox" checked={store.buildingExtrude} onChange={(event) => store.setBuildingExtrude(event.target.checked)}/>{t("building.extrude")}</span></label><div className="building-action-grid"><button type="button" disabled={!selectedId} onClick={() => { click(); if (selectedId) editor.duplicateBuilding(selectedId); }}><Copy size={15}/>{t("building.duplicate")}</button><button type="button" disabled={!selectedId} onClick={() => { click(); if (selectedId) editor.mirrorBuilding(selectedId); }}><FlipHorizontal2 size={15}/>{t("building.mirror")}</button><button type="button" disabled={!selectedId} onClick={() => { click(); if (selectedId) editor.rotateBuilding(selectedId, -Math.PI / 12); }}><RotateCcw size={15}/>{t("building.rotateLeft")}</button><button type="button" disabled={!selectedId} onClick={() => { click(); if (selectedId) editor.rotateBuilding(selectedId, Math.PI / 12); }}><RotateCw size={15}/>{t("building.rotateRight")}</button><button type="button" disabled={!selectedId} onClick={() => { click(); if (selectedId) editor.scaleBuilding(selectedId, 0.9); }}><Minimize size={15}/>{t("building.scaleDown")}</button><button type="button" disabled={!selectedId} onClick={() => { click(); if (selectedId) editor.scaleBuilding(selectedId, 1.1); }}><Maximize size={15}/>{t("building.scaleUp")}</button></div></>}
    <small className="palette-hint">{t(store.buildingMode === "preset" ? "building.help.place" : store.buildingMode === "free" ? "building.help.free" : store.buildingExtrude ? "building.help.extrude" : "building.help.edit")}</small>
  </aside>;
}
