import { Building2, Copy, FlipHorizontal2, Grid2X2, LandPlot, Maximize, Minimize, PenTool, PencilRuler, RotateCcw, RotateCw, Spline, SquareDashedMousePointer, Waypoints } from "lucide-react";
import { useEditorStore } from "../../app/store/editorStore";
import type { Editor } from "../../editor/Editor";
import { ringFootprintRadii, type BuildingPreset } from "../../geometry/BuildingGeometry";
import type { TranslationKey } from "../../i18n";
import type { BuildingStyle, BuildingType } from "../../model/City";

const presets: BuildingPreset[] = ["rectangle", "l", "u", "h", "courtyard", "ring"];
const presetKeys: Record<BuildingPreset, TranslationKey> = { rectangle: "building.preset.rectangle", l: "building.preset.l", u: "building.preset.u", h: "building.preset.h", courtyard: "building.preset.courtyard", ring: "building.preset.ring" };
const typeKeys: Record<BuildingType, TranslationKey> = { residential: "building.type.residential", commercial: "building.type.commercial", education: "building.type.education", medical: "building.type.medical", government: "building.type.government", industrial: "building.type.industrial", office: "building.type.office", public: "building.type.public", custom: "building.type.custom" };
const styleKeys: Record<BuildingStyle, TranslationKey> = { modern: "building.style.modern", chinese: "building.style.chinese", classical: "building.style.classical", industrial: "building.style.industrial", custom: "building.style.custom" };

export function BuildingToolPalette({ editor, t }: { editor: Editor; t: (key: TranslationKey) => string }) {
  const store = useEditorStore(); const selectedId = editor.selection?.kind === "building" ? editor.selection.id : undefined; const selectedBuilding = editor.state.city.buildings.find((building) => building.id === selectedId); const ringRadii = selectedBuilding ? ringFootprintRadii(selectedBuilding.footprint) : undefined;
  const setOuterRadius = (radius: number) => { const value = Math.max(3, radius); store.setBuildingWidth(value * 2); if (store.buildingDepth / 2 >= value) store.setBuildingDepth((value - 1) * 2); };
  const setInnerRadius = (radius: number) => store.setBuildingDepth(Math.max(2, Math.min(radius, store.buildingWidth / 2 - 1)) * 2);
  return <aside className="road-palette building-palette glass-panel" data-building-mode={store.buildingMode} aria-label={t("tools.buildings")}>
    <div className="palette-title"><Building2 size={16}/><span>{t("tools.buildings")}</span></div>
    <div className="palette-toggle building-mode-toggle">
      <button className={store.buildingMode === "preset" ? "is-active" : ""} type="button" onClick={() => store.setBuildingMode("preset")}><Building2 size={16}/><small>{t("building.place")}</small></button>
      <button className={store.buildingMode === "roadside" ? "is-active" : ""} type="button" onClick={() => store.setBuildingMode("roadside")}><LandPlot size={16}/><small>{t("building.roadside")}</small></button>
      <button className={store.buildingMode === "diagonal" ? "is-active" : ""} type="button" onClick={() => store.setBuildingMode("diagonal")}><SquareDashedMousePointer size={16}/><small>{t("building.diagonal")}</small></button>
      <button className={store.buildingMode === "free" ? "is-active" : ""} type="button" onClick={() => store.setBuildingMode("free")}><PenTool size={16}/><small>{t("building.free")}</small></button>
      <button className={store.buildingMode === "road-area" ? "is-active" : ""} type="button" onClick={() => store.setBuildingMode("road-area")}><Grid2X2 size={16}/><small>{t("building.roadArea")}</small></button>
      <button className={store.buildingMode === "edit" ? "is-active" : ""} type="button" onClick={() => store.setBuildingMode("edit")}><PencilRuler size={16}/><small>{t("building.edit")}</small></button>
    </div>
    {store.buildingMode === "preset" && <><small className="zone-section-label">{t("building.preset")}</small><div className="building-preset-grid">{presets.map((preset) => <button className={store.buildingPreset === preset ? "is-active" : ""} type="button" key={preset} onClick={() => store.setBuildingPreset(preset)}><b>{preset === "rectangle" ? "R" : preset === "ring" ? "O" : preset.toUpperCase()}</b><span>{t(presetKeys[preset])}</span></button>)}</div></>}
    {(store.buildingMode === "free" || store.buildingMode === "diagonal") && <div className="palette-toggle edge-style-toggle"><button className={store.buildingEdgeStyle === "straight" ? "is-active" : ""} type="button" onClick={() => store.setBuildingEdgeStyle("straight")}><Waypoints size={16}/><small>{t("shape.straight")}</small></button><button className={store.buildingEdgeStyle === "smooth" ? "is-active" : ""} type="button" onClick={() => store.setBuildingEdgeStyle("smooth")}><Spline size={16}/><small>{t("shape.smooth")}</small></button></div>}
    {store.buildingMode === "road-area" && <div className="building-spacing-control"><Grid2X2 size={15}/><span><b>{t("building.spacing")}</b><label><small>{t("building.minSpacing")}</small><div className="palette-width"><input type="number" min="0" max="200" step="0.5" value={store.buildingMinSpacing} onChange={(event) => store.setBuildingMinSpacing(Number(event.target.value))}/><span>m</span></div></label><label><small>{t("building.maxSpacing")}</small><div className="palette-width"><input type="number" min="0" max="200" step="0.5" value={store.buildingMaxSpacing} onChange={(event) => store.setBuildingMaxSpacing(Number(event.target.value))}/><span>m</span></div></label></span></div>}
    {store.buildingMode !== "edit" && <>
      <label><Building2 size={15}/><select value={store.buildingType} title={t("properties.buildingType")} onChange={(event) => store.setBuildingType(event.target.value as BuildingType)}>{(Object.keys(typeKeys) as BuildingType[]).map((type) => <option key={type} value={type}>{t(typeKeys[type])}</option>)}</select></label>
      <label><span>ST</span><input value={store.buildingSubtype} title={t("building.subtype")} placeholder={t("building.subtype")} onChange={(event) => store.setBuildingSubtype(event.target.value)}/></label>
      <label><PencilRuler size={15}/><select value={store.buildingStyle} title={t("building.style")} onChange={(event) => store.setBuildingStyle(event.target.value as BuildingStyle)}>{(Object.keys(styleKeys) as BuildingStyle[]).map((style) => <option key={style} value={style}>{t(styleKeys[style])}</option>)}</select></label>
      {store.buildingMode === "road-area" ? <>
        <div><label className="zone-section-label" htmlFor="building-min-side-length">{t("building.minSideLength")}</label><div className="palette-width"><input id="building-min-side-length" type="number" min="4" max="500" step="0.5" value={store.buildingMinSideLength} onChange={(event) => store.setBuildingMinSideLength(event.target.valueAsNumber)}/><span>m</span></div></div>
        <div><label className="zone-section-label" htmlFor="building-max-side-length">{t("building.maxSideLength")}</label><div className="palette-width"><input id="building-max-side-length" type="number" min="4" max="500" step="0.5" value={store.buildingMaxSideLength} onChange={(event) => store.setBuildingMaxSideLength(event.target.valueAsNumber)}/><span>m</span></div></div>
        <div><label className="zone-section-label" htmlFor="building-density">{t("building.density")}</label><div className="zone-opacity-control"><input id="building-density" type="range" min="0" max="100" step="5" value={Math.round(store.buildingDensity * 100)} onChange={(event) => store.setBuildingDensity(event.target.valueAsNumber / 100)}/><output htmlFor="building-density">{Math.round(store.buildingDensity * 100)}%</output></div></div>
      </> : store.buildingMode === "preset" && store.buildingPreset === "ring" ? <>
        <label><span title={t("building.outerRadius")}>OR</span><div className="palette-width"><input type="number" min="3" max="250" step="0.5" value={store.buildingWidth / 2} title={t("building.outerRadius")} onChange={(event) => setOuterRadius(Number(event.target.value))}/><span>m</span></div></label>
        <label><span title={t("building.innerRadius")}>IR</span><div className="palette-width"><input type="number" min="2" max={Math.max(2, store.buildingWidth / 2 - 1)} step="0.5" value={Math.min(store.buildingDepth / 2, store.buildingWidth / 2 - 1)} title={t("building.innerRadius")} onChange={(event) => setInnerRadius(Number(event.target.value))}/><span>m</span></div></label>
      </> : store.buildingMode !== "roadside" && <>
        <label><span>W</span><div className="palette-width"><input type="number" min="4" max="500" step="0.5" value={store.buildingWidth} onChange={(event) => store.setBuildingWidth(Number(event.target.value))}/><span>m</span></div></label>
        <label><span>D</span><div className="palette-width"><input type="number" min="4" max="500" step="0.5" value={store.buildingDepth} onChange={(event) => store.setBuildingDepth(Number(event.target.value))}/><span>m</span></div></label>
      </>}
      <label><span>F</span><input type="number" min="1" max="200" value={store.buildingFloors} title={t("building.floors")} onChange={(event) => store.setBuildingFloors(Number(event.target.value))}/></label>
      <label><span>H</span><div className="palette-width"><input type="number" min="1" max="1000" step="0.5" value={store.buildingHeight} onChange={(event) => store.setBuildingHeight(Number(event.target.value))}/><span>m</span></div></label>
      {store.buildingMode !== "roadside" && store.buildingMode !== "road-area" && <label className="palette-check"><span><input type="checkbox" checked={store.buildingSnapToRoad} onChange={(event) => store.setBuildingSnapToRoad(event.target.checked)}/>{t("building.snapToRoad")}</span></label>}
      {store.buildingMode !== "road-area" && (store.buildingMode === "roadside" || store.buildingSnapToRoad) && <label><span title={t("building.setback")}>SB</span><div className="palette-width"><input type="number" min="0" max="200" step="0.5" value={store.buildingSetback} title={t("building.setback")} onChange={(event) => store.setBuildingSetback(Number(event.target.value))}/><span>m</span></div></label>}
    </>}
    {store.buildingMode === "edit" && <>
      {ringRadii && selectedId && <>
        <label><span title={t("building.outerRadius")}>OR</span><div className="palette-width"><input type="number" min="3" max="250" step="0.5" value={Math.round(ringRadii.outerRadius * 2) / 2} title={t("building.outerRadius")} onChange={(event) => editor.resizeRingBuilding(selectedId, Number(event.target.value), ringRadii.innerRadius)}/><span>m</span></div></label>
        <label><span title={t("building.innerRadius")}>IR</span><div className="palette-width"><input type="number" min="1" max={Math.max(1, ringRadii.outerRadius - 1)} step="0.5" value={Math.round(ringRadii.innerRadius * 2) / 2} title={t("building.innerRadius")} onChange={(event) => editor.resizeRingBuilding(selectedId, ringRadii.outerRadius, Number(event.target.value))}/><span>m</span></div></label>
      </>}
      <label className="palette-check"><span><input type="checkbox" checked={store.buildingExtrude} onChange={(event) => store.setBuildingExtrude(event.target.checked)}/>{t("building.extrude")}</span></label>
      <div className="building-action-grid"><button type="button" disabled={!selectedId} onClick={() => { if (selectedId) editor.duplicateBuilding(selectedId); }}><Copy size={15}/>{t("building.duplicate")}</button><button type="button" disabled={!selectedId} onClick={() => { if (selectedId) editor.mirrorBuilding(selectedId); }}><FlipHorizontal2 size={15}/>{t("building.mirror")}</button><button type="button" disabled={!selectedId} onClick={() => { if (selectedId) editor.rotateBuilding(selectedId, -Math.PI / 12); }}><RotateCcw size={15}/>{t("building.rotateLeft")}</button><button type="button" disabled={!selectedId} onClick={() => { if (selectedId) editor.rotateBuilding(selectedId, Math.PI / 12); }}><RotateCw size={15}/>{t("building.rotateRight")}</button><button type="button" disabled={!selectedId} onClick={() => { if (selectedId) editor.scaleBuilding(selectedId, 0.9); }}><Minimize size={15}/>{t("building.scaleDown")}</button><button type="button" disabled={!selectedId} onClick={() => { if (selectedId) editor.scaleBuilding(selectedId, 1.1); }}><Maximize size={15}/>{t("building.scaleUp")}</button></div>
    </>}
    <small className="palette-hint">{t(store.buildingMode === "preset" ? "building.help.place" : store.buildingMode === "roadside" ? "building.help.roadside" : store.buildingMode === "diagonal" ? "building.help.diagonal" : store.buildingMode === "free" ? "building.help.free" : store.buildingMode === "road-area" ? "building.help.roadArea" : store.buildingExtrude ? "building.help.extrude" : "building.help.edit")}</small>
  </aside>;
}
