import { MousePointer2, MoveHorizontal, PenTool, Route, Spline, SquareDashedMousePointer, Trees, Waves, Waypoints } from "lucide-react";
import { useEditorStore } from "../../app/store/editorStore";
import type { TranslationKey } from "../../i18n";

export function WaterToolPalette({ t }: { t: (key: TranslationKey) => string }) {
  const store = useEditorStore();
  return <aside className="road-palette water-palette glass-panel" aria-label={t("tools.water")}>
    <div className="palette-title"><Waves size={17}/><span>{t("tools.water")}</span></div>
    <div className="palette-toggle water-mode-toggle"><button className={store.waterMode === "free" ? "is-active" : ""} type="button" onClick={() => store.setWaterMode("free")}><PenTool size={18}/><small>{t("water.free")}</small></button><button className={store.waterMode === "rectangle" ? "is-active" : ""} type="button" onClick={() => store.setWaterMode("rectangle")}><SquareDashedMousePointer size={18}/><small>{t("water.rectangle")}</small></button><button className={store.waterMode === "river" ? "is-active" : ""} type="button" onClick={() => store.setWaterMode("river")}><Route size={18}/><small>{t("water.river")}</small></button><button className={store.waterMode === "island" ? "is-active" : ""} type="button" onClick={() => store.setWaterMode("island")}><Trees size={18}/><small>{t("water.island")}</small></button><button className={store.waterMode === "edit" ? "is-active" : ""} type="button" onClick={() => store.setWaterMode("edit")}><MousePointer2 size={18}/><small>{t("water.edit")}</small></button></div>
    {store.waterMode === "river" && <label><MoveHorizontal size={15}/><div className="palette-width"><input type="number" min="1" max="500" step="0.5" value={store.waterRiverWidth} title={t("water.riverWidth")} onChange={(event) => store.setWaterRiverWidth(event.target.valueAsNumber)}/><span>m</span></div></label>}
    {store.waterMode !== "edit" && <div className="palette-toggle edge-style-toggle"><button className={store.waterEdgeStyle === "straight" ? "is-active" : ""} type="button" onClick={() => store.setWaterEdgeStyle("straight")}><Waypoints size={16}/><small>{t("shape.straight")}</small></button><button className={store.waterEdgeStyle === "smooth" ? "is-active" : ""} type="button" onClick={() => store.setWaterEdgeStyle("smooth")}><Spline size={16}/><small>{t("shape.smooth")}</small></button></div>}
    {store.waterMode === "island" && <><small className="zone-section-label">{t("landscaping.shade")}</small><label className="zone-style-control"><span className="zone-color-dot" style={{ background: store.landscapingColor }}/><input type="color" value={store.landscapingColor} onChange={(event) => store.setLandscapingColor(event.target.value)}/></label><small className="zone-section-label">{t("landscaping.depth")}</small><label className="zone-opacity-control"><input type="range" min="0.15" max="1" step="0.05" value={store.landscapingOpacity} onChange={(event) => store.setLandscapingOpacity(Number(event.target.value))}/><output>{Math.round(store.landscapingOpacity * 100)}%</output></label></>}
    <small className="palette-hint">{t(store.waterMode === "free" ? "water.help.free" : store.waterMode === "rectangle" ? "water.help.rectangle" : store.waterMode === "river" ? "water.help.river" : store.waterMode === "island" ? "water.help.island" : "water.help.edit")}</small>
  </aside>;
}
