import { ArrowDown, ArrowUp, Check, Eye, GraduationCap, GripVertical, Hospital as HospitalIcon, Layers3, Plus, Trash2, Wand2, X } from "lucide-react";
import { useEffect, useState, type KeyboardEvent } from "react";
import type { EditorTool, LayerId, LayerVisibility } from "../../app/store/editorStore";
import type { Editor } from "../../editor/Editor";
import type { TranslationKey } from "../../i18n";
import { type Building, type BuildingStyle, type BuildingType, type BusLine, type BusStop, type BusStopSide, type EducationLevel, type Hospital, type Park, type RailLine, type RailStation, type RailTrack, type Road, type RoadCategory, type RoadGeometry, type RoadStructure, type RoadSubtype, type University, type WaterArea, type Zone, type ZoneType } from "../../model/City";
import { selectedRoadEdge, selectedRoadEdges, type RoadSelectionScope } from "../../editor/RoadIdentity";
import { formatZoneArea, formatZonePerimeter, zoneArea, zonePerimeter } from "../../geometry/ZoneGeometry";
import { defaultZoneColors, defaultZoneIconColors, defaultZoneIcons, editableZoneTypes, zoneIconIds } from "../../model/ZoneStyle";
import { buildingArea, buildingPerimeter } from "../../geometry/BuildingGeometry";
import { busStationLines } from "../../geometry/BusGeometry";
import type { FacilityPOI } from "../../model/City";
import { facilityTypeName } from "../../model/FacilityCatalog";
import { useEditorStore } from "../../app/store/editorStore";
import { formatWaterArea, waterArea, waterPerimeter } from "../../geometry/WaterGeometry";
import { UniversityPanel } from "./UniversityPanel";
import { HospitalPanel } from "./HospitalPanel";
import { CompanyPanel } from "./CompanyPanel";
import { DistrictPanel } from "./DistrictPanel";
import { universityLogoUrl } from "../../model/UniversityLogoCatalog";

const layers: Array<{ id: LayerId; key: TranslationKey }> = [
  { id: "baseMap", key: "layers.baseMap" }, { id: "roads", key: "layers.roads" }, { id: "buildings", key: "layers.buildings" }, { id: "facilities", key: "layers.facilities" }, { id: "poi", key: "layers.poi" }, { id: "transit", key: "layers.transit" }, { id: "parks", key: "layers.parks" }, { id: "districts", key: "layers.districts" }, { id: "water", key: "layers.water" }, { id: "labels", key: "layers.labels" }, { id: "zoning", key: "layers.zoning" }, { id: "grid", key: "layers.grid" },
];
const subtypeKeys: Record<RoadSubtype, TranslationKey> = { large: "road.subtype.large", medium: "road.subtype.medium", small: "road.subtype.small", pedestrian: "road.subtype.pedestrian", highway: "road.subtype.highway", ramp: "road.subtype.ramp" };
const structureKeys: Record<RoadStructure, TranslationKey> = { ground: "road.structure.ground", elevated: "road.structure.elevated", tunnel: "road.structure.tunnel" };
const categoryKeys: Record<RoadCategory, TranslationKey> = { normal: "road.category.normal", pedestrian: "road.category.pedestrian", highway: "road.category.highway" };
const zoneTypeKeys: Record<Exclude<ZoneType, "public">, TranslationKey> = { residential: "zone.type.residential", commercial: "zone.type.commercial", education: "zone.type.education", medical: "zone.type.medical", government: "zone.type.government", industrial: "zone.type.industrial", office: "zone.type.office", green: "zone.type.green", tourism: "zone.type.tourism", zoo: "zone.type.zoo", "amusement-park": "zone.type.amusement-park", "golf-course": "zone.type.golf-course", resort: "zone.type.resort", "high-speed-rail-station": "zone.type.high-speed-rail-station", "train-station": "zone.type.train-station", airport: "zone.type.airport", mixed: "zone.type.mixed", custom: "zone.type.custom" };
const buildingTypeKeys: Record<BuildingType, TranslationKey> = { residential: "building.type.residential", commercial: "building.type.commercial", education: "building.type.education", medical: "building.type.medical", government: "building.type.government", office: "building.type.office", industrial: "building.type.industrial", public: "building.type.public", custom: "building.type.custom" };
const buildingStyleKeys: Record<BuildingStyle, TranslationKey> = { modern: "building.style.modern", chinese: "building.style.chinese", classical: "building.style.classical", industrial: "building.style.industrial", custom: "building.style.custom" };
const educationLevels: EducationLevel[] = ["kindergarten", "primary", "middle", "high", "vocational", "college", "university", "special", "other"];
const educationLevelKeys: Record<EducationLevel, TranslationKey> = { kindergarten: "education.kindergarten", primary: "education.primary", middle: "education.middle", high: "education.high", vocational: "education.vocational", college: "education.college", university: "education.university", special: "education.special", other: "education.other" };

function DescriptionField({ value, readOnly = false, allowEqualCommit = false, t, onCommit }: { value?: string; readOnly?: boolean; allowEqualCommit?: boolean; t: (key: TranslationKey) => string; onCommit?: (value: string) => void }) {
  const [description, setDescription] = useState(value ?? ""); const [dirty, setDirty] = useState(false); useEffect(() => { setDescription(value ?? ""); setDirty(false); }, [value]);
  return <details className="description-editor"><summary>{t("common.description")}</summary>{readOnly ? <p>{value?.trim() || t("common.descriptionEmpty")}</p> : <textarea value={description} placeholder={t("common.descriptionPlaceholder")} onChange={(event) => { setDescription(event.target.value); setDirty(true); }} onBlur={() => { if (dirty && (allowEqualCommit || description !== (value ?? ""))) onCommit?.(description); setDirty(false); }}/>}</details>;
}

function commitOnEnter(event: KeyboardEvent<HTMLInputElement>): void { if (event.key === "Enter") { event.preventDefault(); event.currentTarget.blur(); } }

function RoadPropertyForm({ editor, road, edgeId, edgeIds, edgeName, groupSize, nodeCount, scope, structure, geometry, mixed, t }: { editor: Editor; road: Road; edgeId: string; edgeIds: string[]; edgeName: string; groupSize: number; nodeCount: number; scope: RoadSelectionScope | "multi"; structure: RoadStructure; geometry: RoadGeometry; mixed: { name: boolean; category: boolean; subtype: boolean; width: boolean; structure: boolean; description: boolean }; t: (key: TranslationKey) => string }) {
  const [name, setName] = useState(edgeName); const [nameDirty, setNameDirty] = useState(false);
  const [width, setWidth] = useState(mixed.width ? "" : String(road.width));
  useEffect(() => { setName(edgeName); setNameDirty(false); setWidth(mixed.width ? "" : String(road.width)); }, [edgeId, edgeName, road.width, mixed.width]);
  const commitWidth = () => {
    if (!width.trim()) return;
    const parsed = Number(width);
    const value = Number.isFinite(parsed) ? Math.max(2, Math.min(60, Math.round(parsed * 2) / 2)) : road.width;
    setWidth(String(value));
    if (mixed.width || value !== road.width) editor.updateRoadEdgesStyle(edgeIds, { width: value });
  };
  return <div className="property-form">
    <p><b>{t("properties.renameScope")}</b>{t(scope === "logical" ? "properties.renameGroup" : scope === "multi" ? "properties.multiSelection" : "properties.renameSegment")}</p>
    <label>{t("common.name")}<input value={name} placeholder={mixed.name ? t("properties.mixed") : undefined} onChange={(event) => { setName(event.target.value); setNameDirty(true); }} onBlur={() => { if (nameDirty && (mixed.name || name !== edgeName)) editor.renameRoadEdges(edgeIds, name); setNameDirty(false); }} onKeyDown={commitOnEnter}/></label>
    <label>{t("properties.category")}<select value={mixed.category ? "" : road.category} onChange={(event) => editor.updateRoadEdgesStyle(edgeIds, { category: event.target.value as RoadCategory })}>{mixed.category && <option value="" disabled>{t("properties.mixed")}</option>}{(Object.keys(categoryKeys) as RoadCategory[]).map((value) => <option key={value} value={value}>{t(categoryKeys[value])}</option>)}</select></label>
    <label>{t("properties.subtype")}<select value={mixed.subtype ? "" : road.subtype} onChange={(event) => editor.updateRoadEdgesStyle(edgeIds, { subtype: event.target.value as RoadSubtype })}>{mixed.subtype && <option value="" disabled>{t("properties.mixed")}</option>}{(Object.keys(subtypeKeys) as RoadSubtype[]).map((value) => <option key={value} value={value}>{t(subtypeKeys[value])}</option>)}</select></label>
    <label>{t("common.width")}<div className="unit-input"><input type="number" min="2" max="60" step="0.5" value={width} onChange={(event) => setWidth(event.target.value)} onBlur={commitWidth} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }}/><span>m</span></div></label>
    <label>{t("properties.structure")}<select value={mixed.structure ? "" : structure} onChange={(event) => editor.updateRoadEdgesStructure(edgeIds, event.target.value as RoadStructure)}>{mixed.structure && <option value="" disabled>{t("properties.mixed")}</option>}{(Object.keys(structureKeys) as RoadStructure[]).map((value) => <option key={value} value={value}>{t(structureKeys[value])}</option>)}</select></label>
    {edgeIds.length === 1 && <label>{t("road.drawMode")}<select value={geometry.type === "line" ? "line" : "curve"} onChange={(event) => editor.updateRoadEdgeGeometry(edgeId, event.target.value as "line" | "curve")}><option value="line">{t("road.straight")}</option><option value="curve">{t("road.curve")}</option></select></label>}
    <p>{t("properties.segmentCount")}: {groupSize}</p>
    {nodeCount > 0 && <p>{t("properties.nodeCount")}: {nodeCount}</p>}
    <DescriptionField value={mixed.description ? "" : road.description} allowEqualCommit={mixed.description} t={t} onCommit={(description) => editor.updateRoadEdgesStyle(edgeIds, { description })}/>
    {edgeIds.length === 1 && <button className="secondary-action" type="button" disabled={geometry.type === "line"} onClick={() => editor.updateRoadEdgeGeometry(edgeId, "line")}><Wand2 size={16}/>{t("properties.straighten")}</button>}{scope !== "multi" && <button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button>}
  </div>;
}

function ZonePropertyForm({ editor, zone, readOnly, t }: { editor: Editor; zone: Zone; readOnly: boolean; t: (key: TranslationKey) => string }) {
  const [name, setName] = useState(zone.name ?? ""); const [opacity, setOpacity] = useState(zone.opacity);
  useEffect(() => { setName(zone.name ?? ""); setOpacity(zone.opacity); }, [zone.id, zone.name, zone.opacity]);
  const commitOpacity = () => { if (Math.abs(opacity - zone.opacity) > 0.001) editor.updateZone(zone.id, { opacity }); };
  const affiliatedUniversity = zone.affiliatedUniversityId ? editor.state.city.universities.find((university) => university.id === zone.affiliatedUniversityId) : undefined;
  if (readOnly) return <div className="property-form property-view"><p><b>{t("common.name")}</b>{zone.name?.trim() || "-"}</p><p><b>{t("zone.type")}</b>{zone.type === "public" ? zone.type : t(zoneTypeKeys[zone.type])}</p>{affiliatedUniversity && <p><b>{t("education.affiliatedUniversity")}</b>{affiliatedUniversity.name || t("university.unnamedUniversity")}</p>}<p><b>{t("zone.opacity")}</b>{Math.round(zone.opacity * 100)}%</p><p><b>{t("zone.area")}</b>{formatZoneArea(zoneArea(zone.polygon))}</p><p><b>{t("zone.perimeter")}</b>{formatZonePerimeter(zonePerimeter(zone.polygon))}</p><p><b>{t("zone.source")}</b>{t(zone.source === "custom" ? "zone.source.custom" : "zone.source.road-fill")}</p><DescriptionField value={zone.description} readOnly t={t}/></div>;
  const legacyType = !(editableZoneTypes as readonly ZoneType[]).includes(zone.type);
  return <div className="property-form">
    <label>{t("common.name")}<input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => { if (name !== (zone.name ?? "")) editor.updateZone(zone.id, { name }); }} onKeyDown={commitOnEnter}/></label>
    <label>{t("zone.type")}<select value={zone.type} onChange={(event) => { const type = event.target.value as ZoneType; editor.updateZone(zone.id, { type, color: type === "custom" ? zone.color : defaultZoneColors[type], icon: type === "custom" ? zone.icon : defaultZoneIcons[type], iconColor: type === "custom" ? zone.iconColor : defaultZoneIconColors[type], iconOpacity: type === "custom" ? zone.iconOpacity : 1, educationLevel: type === "education" ? zone.educationLevel : undefined, affiliatedUniversityId: type === "education" || type === "medical" ? zone.affiliatedUniversityId : undefined, hospitalId: type === "medical" ? zone.hospitalId : undefined, hospitalCampusRole: type === "medical" ? zone.hospitalCampusRole : undefined, hospital: type === "medical" ? zone.hospital : undefined }); }}>{legacyType && <option value={zone.type}>{zone.type === "public" ? zone.type : t(zoneTypeKeys[zone.type])}</option>}{editableZoneTypes.map((type) => <option key={type} value={type}>{t(zoneTypeKeys[type])}</option>)}</select></label>
    {zone.type === "education" && !zone.universityId && <label>{t("education.level")}<select value={zone.educationLevel ?? ""} onChange={(event) => editor.updateZone(zone.id, { educationLevel: event.target.value as EducationLevel })}><option value="" disabled>{t("education.chooseLevel")}</option>{educationLevels.map((level) => <option key={level} value={level}>{t(educationLevelKeys[level])}</option>)}</select></label>}
    {(zone.type === "education" || zone.type === "medical") && !zone.universityId && <label>{t("education.affiliatedUniversity")}<select value={zone.affiliatedUniversityId ?? ""} onChange={(event) => editor.updateZone(zone.id, { affiliatedUniversityId: event.target.value || undefined })}><option value="">{t("education.independent")}</option>{editor.state.city.universities.map((university) => <option key={university.id} value={university.id}>{university.name || t("university.unnamedUniversity")}</option>)}</select></label>}
    {zone.type === "custom" && <><label>{t("zone.color")}<input type="color" value={zone.color ?? defaultZoneColors.custom} onChange={(event) => editor.updateZone(zone.id, { color: event.target.value })}/></label><label>{t("zone.icon")}<select value={zone.icon ?? zoneIconIds[0]} onChange={(event) => editor.updateZone(zone.id, { icon: event.target.value })}>{zoneIconIds.map((icon) => <option key={icon} value={icon}>{icon}</option>)}</select></label><label>{t("zone.iconColor")}<input type="color" value={zone.iconColor ?? defaultZoneIconColors.custom} onChange={(event) => editor.updateZone(zone.id, { iconColor: event.target.value })}/></label><label>{t("zone.iconOpacity")}<div className="opacity-control"><input type="range" min="0" max="1" step="0.05" value={zone.iconOpacity ?? 1} onChange={(event) => editor.updateZone(zone.id, { iconOpacity: Number(event.target.value) })}/><output>{Math.round((zone.iconOpacity ?? 1) * 100)}%</output></div></label></>}
    <label>{t("zone.opacity")}<div className="opacity-control"><input type="range" min="0.05" max="1" step="0.05" value={opacity} onChange={(event) => setOpacity(Number(event.target.value))} onPointerUp={commitOpacity} onBlur={commitOpacity}/><output>{Math.round(opacity * 100)}%</output></div></label>
    <p>{t("zone.area")}: {formatZoneArea(zoneArea(zone.polygon))}</p><p>{t("zone.perimeter")}: {formatZonePerimeter(zonePerimeter(zone.polygon))}</p><p>{t("zone.source")}: {t(zone.source === "custom" ? "zone.source.custom" : "zone.source.road-fill")}</p>
    <DescriptionField value={zone.description} t={t} onCommit={(description) => editor.updateZone(zone.id, { description })}/>
    <button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button>
  </div>;
}

function BuildingPropertyForm({ editor, building, t }: { editor: Editor; building: Building; t: (key: TranslationKey) => string }) {
  const [name, setName] = useState(building.name ?? ""); const [subtype, setSubtype] = useState(building.subtype); const [floors, setFloors] = useState(String(building.floors)); const [height, setHeight] = useState(String(building.height));
  useEffect(() => { setName(building.name ?? ""); setSubtype(building.subtype); setFloors(String(building.floors)); setHeight(String(building.height)); }, [building.id, building.name, building.subtype, building.floors, building.height]);
  const commitNumber = (field: "floors" | "height", text: string) => { const parsed = Number(text); const value = field === "floors" ? Math.max(1, Math.min(200, Math.round(parsed))) : Math.max(1, Math.min(1000, Math.round(parsed * 2) / 2)); if (!Number.isFinite(value)) { if (field === "floors") setFloors(String(building.floors)); else setHeight(String(building.height)); return; } if (value !== building[field]) editor.updateBuilding(building.id, { [field]: value }); };
  return <div className="property-form"><label>{t("common.name")}<input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => { if (name !== (building.name ?? "")) editor.updateBuilding(building.id, { name }); }} onKeyDown={commitOnEnter}/></label><label>{t("properties.buildingType")}<select value={building.type} onChange={(event) => editor.updateBuilding(building.id, { type: event.target.value as BuildingType })}>{(Object.keys(buildingTypeKeys) as BuildingType[]).map((type) => <option key={type} value={type}>{t(buildingTypeKeys[type])}</option>)}</select></label><label>{t("building.subtype")}<input value={subtype} onChange={(event) => setSubtype(event.target.value)} onBlur={() => { if (subtype !== building.subtype) editor.updateBuilding(building.id, { subtype }); }}/></label><p>{t("building.area")}: {formatZoneArea(buildingArea(building.footprint))}</p><p>{t("building.perimeter")}: {formatZonePerimeter(buildingPerimeter(building.footprint))}</p><label>{t("building.floors")}<input type="number" min="1" max="200" value={floors} onChange={(event) => setFloors(event.target.value)} onBlur={() => commitNumber("floors", floors)} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }}/></label><label>{t("building.height")}<div className="unit-input"><input type="number" min="1" max="1000" step="0.5" value={height} onChange={(event) => setHeight(event.target.value)} onBlur={() => commitNumber("height", height)} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }}/><span>m</span></div></label><label>{t("building.style")}<select value={building.style} onChange={(event) => editor.updateBuilding(building.id, { style: event.target.value as BuildingStyle })}>{(Object.keys(buildingStyleKeys) as BuildingStyle[]).map((style) => <option key={style} value={style}>{t(buildingStyleKeys[style])}</option>)}</select></label><DescriptionField value={building.description} t={t} onCommit={(description) => editor.updateBuilding(building.id, { description })}/><button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button></div>;
}

function BuildingMultiPropertyForm({ editor, buildings, t }: { editor: Editor; buildings: Building[]; t: (key: TranslationKey) => string }) {
  const ids = buildings.map((building) => building.id); const common = <K extends keyof Building>(field: K): Building[K] | undefined => buildings.every((building) => building[field] === buildings[0]?.[field]) ? buildings[0]?.[field] : undefined; const [subtype, setSubtype] = useState(common("subtype") ?? ""); const [subtypeDirty, setSubtypeDirty] = useState(false); const [floors, setFloors] = useState(common("floors") === undefined ? "" : String(common("floors"))); const [height, setHeight] = useState(common("height") === undefined ? "" : String(common("height")));
  useEffect(() => { const first = buildings[0]; setSubtype(buildings.every((building) => building.subtype === first?.subtype) ? first?.subtype ?? "" : ""); setSubtypeDirty(false); setFloors(buildings.every((building) => building.floors === first?.floors) ? String(first?.floors ?? "") : ""); setHeight(buildings.every((building) => building.height === first?.height) ? String(first?.height ?? "") : ""); }, [buildings]);
  const commitNumber = (field: "floors" | "height", draft: string) => { const parsed = Number(draft); if (!draft.trim() || !Number.isFinite(parsed)) return; const value = field === "floors" ? Math.max(1, Math.min(200, Math.round(parsed))) : Math.max(1, Math.min(1000, Math.round(parsed * 2) / 2)); if (field === "floors") setFloors(String(value)); else setHeight(String(value)); editor.updateBuildings(ids, { [field]: value }); };
  const type = common("type"); const style = common("style"); const totalArea = buildings.reduce((sum, building) => sum + buildingArea(building.footprint), 0);
  return <div className="property-form">
    <p><b>{t("building.selectionCount")}</b>{buildings.length}</p><p><b>{t("building.totalArea")}</b>{formatZoneArea(totalArea)}</p>
    <label>{t("properties.buildingType")}<select value={type ?? ""} onChange={(event) => editor.updateBuildings(ids, { type: event.target.value as BuildingType })}>{type === undefined && <option value="" disabled>{t("properties.mixed")}</option>}{(Object.keys(buildingTypeKeys) as BuildingType[]).map((value) => <option key={value} value={value}>{t(buildingTypeKeys[value])}</option>)}</select></label>
    <label>{t("building.subtype")}<input value={subtype} placeholder={common("subtype") === undefined ? t("properties.mixed") : undefined} onChange={(event) => { setSubtype(event.target.value); setSubtypeDirty(true); }} onBlur={() => { if (subtypeDirty) editor.updateBuildings(ids, { subtype }); setSubtypeDirty(false); }} onKeyDown={commitOnEnter}/></label>
    <label>{t("building.floors")}<input type="number" min="1" max="200" value={floors} placeholder={t("properties.mixed")} onChange={(event) => setFloors(event.target.value)} onBlur={() => commitNumber("floors", floors)} onKeyDown={commitOnEnter}/></label>
    <label>{t("building.height")}<div className="unit-input"><input type="number" min="1" max="1000" step="0.5" value={height} placeholder={t("properties.mixed")} onChange={(event) => setHeight(event.target.value)} onBlur={() => commitNumber("height", height)} onKeyDown={commitOnEnter}/><span>m</span></div></label>
    <label>{t("building.style")}<select value={style ?? ""} onChange={(event) => editor.updateBuildings(ids, { style: event.target.value as BuildingStyle })}>{style === undefined && <option value="" disabled>{t("properties.mixed")}</option>}{(Object.keys(buildingStyleKeys) as BuildingStyle[]).map((value) => <option key={value} value={value}>{t(buildingStyleKeys[value])}</option>)}</select></label>
    <button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button>
  </div>;
}

function WaterPropertyForm({ editor, water, t }: { editor: Editor; water: WaterArea; t: (key: TranslationKey) => string }) {
  const [name, setName] = useState(water.name ?? ""); useEffect(() => setName(water.name ?? ""), [water.id, water.name]);
  return <div className="property-form property-view"><label>{t("common.name")}<input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => { if (name !== (water.name ?? "")) editor.updateWater(water.id, { name }); }} onKeyDown={commitOnEnter}/></label><p><b>{t("water.area")}</b>{formatWaterArea(waterArea(water.points))}</p><p><b>{t("water.perimeter")}</b>{formatZonePerimeter(waterPerimeter(water.points))}</p><button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button></div>;
}

function ParkPropertyForm({ editor, park, t }: { editor: Editor; park: Park; t: (key: TranslationKey) => string }) {
  const [name, setName] = useState(park.name ?? ""); useEffect(() => setName(park.name ?? ""), [park.id, park.name]);
  return <div className="property-form property-view"><label>{t("common.name")}<input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => { if (name !== (park.name ?? "")) editor.updatePark(park.id, { name }); }} onKeyDown={commitOnEnter}/></label><label>{t("landscaping.shade")}<input type="color" value={park.color} onChange={(event) => editor.updatePark(park.id, { color: event.target.value })}/></label><label>{t("landscaping.depth")}<div className="opacity-control"><input type="range" min="0.15" max="1" step="0.05" value={park.opacity} onChange={(event) => editor.updatePark(park.id, { opacity: Number(event.target.value) })}/><output>{Math.round(park.opacity * 100)}%</output></div></label><p><b>{t("landscaping.area")}</b>{formatZoneArea(zoneArea(park.points))}</p><p><b>{t("landscaping.perimeter")}</b>{formatZonePerimeter(zonePerimeter(park.points))}</p><p><b>{t("landscaping.source")}</b>{t(park.waterId ? "landscaping.source.island" : park.source === "road-fill" ? "landscaping.source.road-fill" : "landscaping.source.custom")}</p><button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button></div>;
}

function FacilityPropertyForm({ editor, facility, t }: { editor: Editor; facility: FacilityPOI; t: (key: TranslationKey) => string }) {
  const locale = useEditorStore((state) => state.locale); const [name, setName] = useState(facility.name);
  useEffect(() => setName(facility.name), [facility.id, facility.name]);
  const university = facility.affiliatedUniversityId && facility.universityAffiliationKind === "facility" ? editor.state.city.universities.find((item) => item.id === facility.affiliatedUniversityId) : undefined;
  return <div className="property-form property-view"><label>{t("common.name")}<input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => { if (name !== facility.name) editor.updateFacility(facility.id, { name }); }} onKeyDown={commitOnEnter}/></label><p><b>{t("facility.type")}</b>{facilityTypeName(facility.type, locale)}</p>{university && <p><b>{t("university.tab.affiliates")}</b>{university.name}</p>}<label>{t("common.description")}<textarea rows={4} defaultValue={facility.description ?? ""} onBlur={(event) => { if (event.currentTarget.value !== (facility.description ?? "")) editor.updateFacility(facility.id, { description: event.currentTarget.value }); }}/></label><label>{t("facility.color")}<input type="color" value={facility.color} onChange={(event) => editor.updateFacility(facility.id, { color: event.target.value })}/></label><button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button></div>;
}

function StandaloneUniversity({ editor, university, t }: { editor: Editor; university: University; t: (key: TranslationKey) => string }) { const logo = universityLogoUrl(university.logo); const campuses = editor.state.city.zones.filter((zone) => zone.universityId === university.id).length; return <div className="property-form property-view entity-summary"><span className="entity-summary-logo">{logo ? <img src={logo} alt=""/> : <GraduationCap size={30}/>}</span><p><b>{t("common.name")}</b>{university.name || t("university.unnamedUniversity")}</p><p><b>{t("university.ranking")}</b>{university.ranking === null ? t("information.unset") : university.ranking}</p><p><b>{t("university.campusCount")}</b>{campuses}</p><p><b>{t("university.tags")}</b>{university.tags.join(", ") || t("information.unset")}</p><DescriptionField value={university.description} readOnly t={t}/></div>; }
function StandaloneHospital({ editor, hospital, t }: { editor: Editor; hospital: Hospital; t: (key: TranslationKey) => string }) { const university = hospital.affiliatedUniversityId ? editor.state.city.universities.find((item) => item.id === hospital.affiliatedUniversityId) : undefined; return <div className="property-form property-view entity-summary"><span className="entity-summary-logo"><HospitalIcon size={30}/></span><p><b>{t("common.name")}</b>{hospital.name || t("hospital.unnamed")}</p><p><b>{t("hospital.ranking")}</b>{hospital.ranking === null ? t("information.unset") : hospital.ranking}</p><p><b>{t("hospital.affiliatedUniversity")}</b>{university?.name || t("information.unset")}</p><p><b>{t("hospital.tab.specialties")}</b>{hospital.specialties.join(", ") || t("information.unset")}</p><DescriptionField value={hospital.description} readOnly t={t}/></div>; }

function BusLinePropertyForm({ editor, line, t, onExtend }: { editor: Editor; line: BusLine; t: (key: TranslationKey) => string; onExtend: (lineId: string, endpoint: "start" | "end") => void }) {
  const [name, setName] = useState(line.name);
  useEffect(() => setName(line.name), [line.id, line.name]);
  const stops = line.stopIds.map((id) => editor.state.city.busStops.find((stop) => stop.id === id)).filter((stop): stop is BusStop => Boolean(stop));
  return <div className="property-form property-view">
    <label>{t("common.name")}<input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => { if (name !== line.name) editor.updateBusLine(line.id, { name }); }} onKeyDown={commitOnEnter}/></label>
    <label>{t("bus.lineColor")}<input type="color" value={line.color} onChange={(event) => editor.updateBusLine(line.id, { color: event.target.value })}/></label>
    <p><b>{t("bus.routeType")}</b>{t(line.loop ? "bus.routeType.loop" : "bus.routeType.legacy")}</p>
    <p><b>{t("bus.pathSegmentCount")}</b>{line.path.length}</p><p><b>{t("bus.stopCount")}</b>{line.stopIds.length}</p><p><b>{t("bus.direction")}</b>{t(line.loop ? "bus.direction.loop" : "bus.direction.open")}</p>
    <div className="bus-stop-names"><b>{t("bus.stations")}</b>{stops.length > 0 ? <ol>{stops.map((stop) => <li key={stop.id}>{stop.name}</li>)}</ol> : <span>-</span>}</div>
    {!line.loop && !line.startTerminalId && !line.endTerminalId && stops.length >= 2 && <>
      <button type="button" onClick={() => onExtend(line.id, "start")}><Plus size={16}/>{t("bus.newStart")}</button>
      <button type="button" onClick={() => onExtend(line.id, "end")}><Plus size={16}/>{t("bus.newEnd")}</button>
      <small className="palette-hint">{t("bus.help.extend")}</small>
    </>}
    <button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button>
  </div>;
}

function BusStopPropertyForm({ editor, stop, t }: { editor: Editor; stop: BusStop; t: (key: TranslationKey) => string }) {
  const [name, setName] = useState(stop.name); const [fraction, setFraction] = useState(String(stop.fraction));
  useEffect(() => { setName(stop.name); setFraction(String(stop.fraction)); }, [stop.id, stop.name, stop.fraction]);
  const line = (editor.state.city.busLines ?? []).find((candidate) => candidate.id === stop.lineId);
  const transferLines = busStationLines(editor.state.city, stop).filter((candidate) => candidate.id !== stop.lineId);
  const roadEdge = editor.state.city.roadEdges.find((edge) => edge.id === stop.roadEdgeId);
  const commitFraction = () => {
    const parsed = Number(fraction); const value = Number.isFinite(parsed) ? Math.max(0, Math.min(1, parsed)) : stop.fraction;
    setFraction(String(value)); if (value !== stop.fraction) editor.updateBusStop(stop.id, { fraction: value });
  };
  return <div className="property-form property-view">
    <label>{t("common.name")}<input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => { if (name !== stop.name) editor.updateBusStop(stop.id, { name }); }} onKeyDown={commitOnEnter}/></label>
    <p><b>{t("bus.lineName")}</b>{line?.name ?? "-"}</p><div className="bus-transfer-lines"><b>{t("bus.transferLines")}</b>{transferLines.length > 0 ? <ul>{transferLines.map((transferLine) => <li key={transferLine.id}><i style={{ backgroundColor: transferLine.color }}/><span>{transferLine.name}</span></li>)}</ul> : <span>{t("bus.noTransferLines")}</span>}</div><p><b>{t("bus.roadEdge")}</b>{roadEdge?.name ?? stop.roadEdgeId}</p>
    <label>{t("bus.fraction")}<input type="number" min="0" max="1" step="0.01" value={fraction} onChange={(event) => setFraction(event.target.value)} onBlur={commitFraction} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }}/></label>
    <label>{t("bus.side")}<select value={stop.side} onChange={(event) => editor.updateBusStop(stop.id, { side: event.target.value as BusStopSide })}><option value="left">{t("bus.side.left")}</option><option value="right">{t("bus.side.right")}</option></select></label>
    <button className="danger-action" type="button" disabled={Boolean(line?.loop && line.stopIds.length <= 2)} onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button>
  </div>;
}

function RailStationPropertyForm({ editor, station, t }: { editor: Editor; station: RailStation; t: (key: TranslationKey) => string }) {
  const [name, setName] = useState(station.name); useEffect(() => setName(station.name), [station.id, station.name]);
  return <div className="property-form property-view"><label>{t("common.name")}<input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => { const next = name.trim(); if (!next) setName(station.name); else if (next !== station.name) editor.updateRailStation(station.id, { name: next }); }} onKeyDown={commitOnEnter}/></label><button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button></div>;
}

function RailTrackPropertyForm({ editor, track, t }: { editor: Editor; track: RailTrack; t: (key: TranslationKey) => string }) {
  return <div className="property-form property-view">{track.system === "train" && <label>{t("properties.structure")}<select value={track.structure} onChange={(event) => editor.updateRailTrack(track.id, { structure: event.target.value as RoadStructure })}>{(Object.keys(structureKeys) as RoadStructure[]).map((value) => <option key={value} value={value}>{t(structureKeys[value])}</option>)}</select></label>}<button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button></div>;
}

function RailLinePropertyForm({ editor, line, t, onModify }: { editor: Editor; line: RailLine; t: (key: TranslationKey) => string; onModify: (lineId: string, action: "start" | "end" | "station") => void }) {
  const [name, setName] = useState(line.name); useEffect(() => setName(line.name), [line.id, line.name]); const stations = line.stationIds.map((id) => editor.state.city.railStations?.find((station) => station.id === id)).filter((station): station is RailStation => Boolean(station));
  const move = (index: number, offset: -1 | 1) => { const stationIds = [...line.stationIds]; const target = index + offset; if (target < 0 || target >= stationIds.length) return; [stationIds[index], stationIds[target]] = [stationIds[target]!, stationIds[index]!]; editor.updateRailLine(line.id, { stationIds }); };
  return <div className="property-form property-view">
    <label>{t("rail.lineName")}<input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => { const next = name.trim(); if (!next) setName(line.name); else if (next !== line.name) editor.updateRailLine(line.id, { name: next }); }} onKeyDown={commitOnEnter}/></label>
    <label>{t("rail.lineColor")}<div className="property-color-control"><input type="color" value={line.color} aria-label={t("rail.lineColor")} onChange={(event) => editor.updateRailLine(line.id, { color: event.target.value })}/><input key={line.color} type="text" defaultValue={line.color.toUpperCase()} aria-label={`${t("rail.lineColor")} HEX`} onBlur={(event) => { const color = event.currentTarget.value.trim(); if (/^#[0-9a-f]{6}$/i.test(color)) editor.updateRailLine(line.id, { color }); else event.currentTarget.value = line.color.toUpperCase(); }} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }}/></div></label>
    <label className="rail-loop-control"><input type="checkbox" checked={line.loop} onChange={(event) => editor.updateRailLine(line.id, { loop: event.target.checked })}/><span>{t("rail.loop")}</span></label>
    {line.system === "metro" && <><button type="button" onClick={() => onModify(line.id, "station")}><Plus size={16}/>{t("rail.addStation")}</button>{!line.loop && <><button type="button" onClick={() => onModify(line.id, "start")}><Plus size={16}/>{t("rail.extendStart")}</button><button type="button" onClick={() => onModify(line.id, "end")}><Plus size={16}/>{t("rail.extendEnd")}</button></>}<small className="palette-hint">{t("rail.help.modifyLine")}</small></>}
    <div className="rail-stop-list"><b>{t("rail.stops")}</b>{stations.map((station, index) => <div key={station.id}><div className="rail-stop-name"><i style={{ backgroundColor: line.color }}/><small>{index + 1}.</small><input key={`${station.id}:${station.name}`} defaultValue={station.name} aria-label={`${index + 1}. ${station.name}`} onBlur={(event) => { const next = event.currentTarget.value.trim(); if (next && next !== station.name) editor.updateRailStation(station.id, { name: next }); else event.currentTarget.value = station.name; }} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }}/></div><button type="button" disabled={index === 0} title={t("rail.stop.up")} onClick={() => move(index, -1)}><ArrowUp size={13}/></button><button type="button" disabled={index === stations.length - 1} title={t("rail.stop.down")} onClick={() => move(index, 1)}><ArrowDown size={13}/></button><button type="button" disabled={stations.length <= 2} title={t("rail.stop.remove")} onClick={() => editor.updateRailLine(line.id, { stationIds: line.stationIds.filter((id) => id !== station.id) })}><X size={13}/></button></div>)}</div>
    <button className="danger-action" type="button" onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button>
  </div>;
}

interface Props { editor: Editor; tool: EditorTool; visibility: LayerVisibility; zoningOpacity: number; onZoningOpacity: (opacity: number) => void; onToggleLayer: (id: LayerId) => void; onExtendBusRoute: (lineId: string, endpoint: "start" | "end" | "station") => void; t: (key: TranslationKey) => string }
export function RightPanel({ editor, tool, visibility, zoningOpacity, onZoningOpacity, onToggleLayer, onExtendBusRoute, t }: Props) {
  const [layersOpen, setLayersOpen] = useState(false); const selection = editor.selection;
  const roadSelection = selection?.kind === "road" ? selection : selection?.kind === "road-control" ? { kind: "road" as const, id: editor.state.city.roadEdges.find((edge) => edge.id === selection.id)?.roadId ?? "", edgeId: selection.id, scope: "segment" as const } : undefined;
  const multiEdges = selection?.kind === "road-multi" ? editor.state.city.roadEdges.filter((edge) => selection.edgeIds.includes(edge.id)) : []; const selectedEdges = roadSelection ? selectedRoadEdges(editor.state.city, roadSelection) : multiEdges; const roadEdge = roadSelection ? selectedRoadEdge(editor.state.city, roadSelection) : multiEdges[0];
  const road = roadEdge ? editor.state.city.roads.find((item) => item.id === roadEdge.roadId) : selection?.kind === "road" ? editor.state.city.roads.find((item) => item.id === selection.id) : undefined;
  const structure = roadEdge?.structure ?? (road ? editor.state.city.roadEdges.find((edge) => edge.roadId === road.id)?.structure ?? "ground" : "ground");
  const scope = selection?.kind === "road-multi" ? "multi" : roadSelection?.scope ?? "logical"; const groupSize = selectedEdges.length || road?.segmentIds.length || 0; const edgeRoads = selectedEdges.map((edge) => editor.state.city.roads.find((candidate) => candidate.id === edge.roadId)).filter((candidate): candidate is Road => Boolean(candidate)); const allSame = <T,>(values: T[]) => values.length < 2 || values.every((value) => value === values[0]); const sameName = allSame(selectedEdges.map((edge) => edge.name)); const mixed = { name: !sameName, category: !allSame(edgeRoads.map((item) => item.category)), subtype: !allSame(edgeRoads.map((item) => item.subtype)), width: !allSame(edgeRoads.map((item) => item.width)), structure: !allSame(selectedEdges.map((edge) => edge.structure)), description: !allSame(edgeRoads.map((item) => item.description)) }; const edgeName = sameName ? roadEdge?.name ?? "" : ""; const multiNodeCount = selection?.kind === "road-multi" ? selection.nodeIds.length : 0;
  const node = selection?.kind === "node" ? editor.state.city.roadNodes.find((item) => item.id === selection.id) : undefined;
  const zone = selection?.kind === "zone" ? editor.state.city.zones.find((item) => item.id === selection.id) : undefined;
  const water = selection?.kind === "water" ? editor.state.city.waters.find((item) => item.id === selection.id) : undefined;
  const park = selection?.kind === "park" ? editor.state.city.parks.find((item) => item.id === selection.id) : undefined;
  const district = selection?.kind === "district" ? editor.state.city.districts.find((item) => item.id === selection.id) : undefined;
  const building = selection?.kind === "building" ? editor.state.city.buildings.find((item) => item.id === selection.id) : undefined;
  const selectedBuildings = selection?.kind === "building-multi" ? editor.state.city.buildings.filter((item) => selection.ids.includes(item.id)) : [];
  const facility = selection?.kind === "facility" ? editor.state.city.facilities.find((item) => item.id === selection.id) : undefined;
  const directUniversity = selection?.kind === "university" ? editor.state.city.universities.find((item) => item.id === selection.id) : undefined;
  const directHospital = selection?.kind === "hospital" ? editor.state.city.hospitals.find((item) => item.id === selection.id) : undefined;
  const directCompany = selection?.kind === "company" ? editor.state.city.companies.find((item) => item.id === selection.id) : undefined;
  const universityCampus = zone?.universityId || zone?.purpose === "university" ? zone : undefined;
  const hospitalZone = zone?.type === "medical" ? zone : undefined;
  const busLine = selection?.kind === "bus-line" ? (editor.state.city.busLines ?? []).find((item) => item.id === selection.id) : undefined;
  const busStop = selection?.kind === "bus-stop" ? (editor.state.city.busStops ?? []).find((item) => item.id === selection.id) : undefined;
  const railStation = selection?.kind === "rail-station" ? editor.state.city.railStations?.find((item) => item.id === selection.id) : undefined;
  const railLine = selection?.kind === "rail-line" ? editor.state.city.railLines?.find((item) => item.id === selection.id) : undefined;
  const railTrack = selection?.kind === "rail-track" ? editor.state.city.railTracks?.find((item) => item.id === selection.id) : undefined;
  return <aside className="right-floating-ui">
    <button className={`layers-orb ${layersOpen ? "is-active" : ""}`} type="button" title={t("layers.title")} onClick={() => setLayersOpen((value) => !value)}><Layers3 size={22}/></button>
    {layersOpen && <section className="floating-panel layers-popover glass-panel"><header><strong>{t("layers.title")}</strong><button type="button" onClick={() => setLayersOpen(false)}><X size={16}/></button></header><div className="layer-list">{layers.map((item) => <div className="layer-item" key={item.id}><button type="button" onClick={() => onToggleLayer(item.id)}><span className={`layer-check ${visibility[item.id] ? "is-checked" : ""}`}>{visibility[item.id] && <Check size={13}/>}</span><span className="layer-name">{t(item.key)}</span><Eye size={16} className={visibility[item.id] ? "" : "is-muted"}/><GripVertical size={15} className="grip"/></button>{item.id === "zoning" && <label className="layer-opacity"><span>{t("zone.layerOpacity")}</span><input type="range" min="0.05" max="1" step="0.05" value={zoningOpacity} onChange={(event) => onZoningOpacity(Number(event.target.value))}/><output>{Math.round(zoningOpacity * 100)}%</output></label>}</div>)}</div></section>}
    {(railStation || railLine || railTrack) && <section className="floating-panel properties-popover glass-panel"><header><strong>{railStation ? t(railStation.system === "metro" ? "properties.metroStation" : "properties.railStation") : railLine ? t(railLine.system === "metro" ? "properties.metroLine" : "properties.railLine") : t(railTrack?.system === "metro" ? "properties.metroTrack" : "properties.railTrack")}</strong><button type="button" onClick={() => editor.select(null)}><X size={16}/></button></header>{railStation ? <RailStationPropertyForm editor={editor} station={railStation} t={t}/> : railLine ? <RailLinePropertyForm editor={editor} line={railLine} t={t} onModify={onExtendBusRoute}/> : railTrack ? <RailTrackPropertyForm editor={editor} track={railTrack} t={t}/> : null}</section>}
    {(road || node || zone || park || district || water || building || selectedBuildings.length > 0 || facility || directUniversity || directHospital || directCompany || busLine || busStop || multiNodeCount > 0) && <section className={`floating-panel properties-popover glass-panel${universityCampus || hospitalZone ? " university-properties-popover" : district || directCompany || facility?.type === "company" ? " entity-properties-popover" : ""}`}>{hospitalZone ? <HospitalPanel editor={editor} campus={hospitalZone} onClose={() => editor.select(null)} t={t}/> : universityCampus ? <UniversityPanel editor={editor} campus={universityCampus} onClose={() => editor.select(null)} t={t}/> : <><header><strong>{directUniversity ? t("information.tab.university") : directHospital ? t("information.tab.hospital") : directCompany || facility?.type === "company" ? t("company.profile") : busLine ? t("properties.busLine") : busStop ? t("properties.busStop") : facility ? t("properties.facility") : zone ? t("properties.zone") : park ? t("properties.park") : district ? t("district.profile") : water ? t("properties.water") : building ? t("properties.building") : selectedBuildings.length ? t("properties.buildings") : road ? t("properties.road") : t("properties.node")}</strong><button type="button" aria-label={t("common.close")} onClick={() => editor.select(null)}><X size={16}/></button></header>
      {directUniversity ? <StandaloneUniversity editor={editor} university={directUniversity} t={t}/> : directHospital ? <StandaloneHospital editor={editor} hospital={directHospital} t={t}/> : directCompany ? <CompanyPanel editor={editor} company={directCompany} t={t}/> : busLine ? <BusLinePropertyForm editor={editor} line={busLine} t={t} onExtend={onExtendBusRoute}/> : busStop ? <BusStopPropertyForm editor={editor} stop={busStop} t={t}/> : facility?.type === "company" ? <CompanyPanel editor={editor} facility={facility} t={t}/> : facility ? <FacilityPropertyForm editor={editor} facility={facility} t={t}/> : zone ? <ZonePropertyForm editor={editor} zone={zone} readOnly={tool === "select" && zone.type !== "education"} t={t}/> : park ? <ParkPropertyForm editor={editor} park={park} t={t}/> : district ? <DistrictPanel key={district.id} editor={editor} district={district} t={t}/> : water ? <WaterPropertyForm editor={editor} water={water} t={t}/> : building ? <BuildingPropertyForm editor={editor} building={building} t={t}/> : selectedBuildings.length ? <BuildingMultiPropertyForm editor={editor} buildings={selectedBuildings} t={t}/> : road && roadEdge ? <RoadPropertyForm editor={editor} road={road} edgeId={roadEdge.id} edgeIds={selectedEdges.map((edge) => edge.id)} edgeName={edgeName} groupSize={groupSize} nodeCount={multiNodeCount} scope={scope} structure={structure} geometry={roadEdge.geometry} mixed={mixed} t={t}/> : node ? <div className="property-form"><p>{t("properties.coordinates")}: {node.x.toFixed(1)}, {node.y.toFixed(1)}</p><button className="danger-action" type="button" disabled={!editor.canDissolveRoadNode(node.id)} onClick={() => editor.deleteSelected()}><Trash2 size={16}/>{t("common.delete")}</button></div> : <div className="property-form"><p>{t("properties.nodeCount")}: {multiNodeCount}</p></div>}</>}
    </section>}
  </aside>;
}
